aliases:
  David Freiheit:
  - Viva Frei
  - Viva Fry
  - Viva
  - Viva Barnes
  - Viva Freiheit
  Robert Barnes:
  - Barnes
  Sheila Gunn Reid:
  - Sheila Gunn-Reed
  Adam Soos:
  - Adam Sos
  Artur Pawlowski:
  - Pastor Artur Pawlowski
  Gad Saad:
  - Dr. Gad Saad
  James Lindsay:
  - Dr. James Lindsay
  Pastor Tim Stephens:
  - Tim Stephens
  Patrick Moore:
  - Dr. Patrick Moore
  W. Keith Campbell:
  - Dr. W. Keith Campbell
  Phil Hutchings:
  - Pastor Phil Hutchings
  Karim Elayoubi:
  - Dr. Karim Elayoubi
  Carol Swain:
  - Dr. Carol Swain
  Tony Abbott:
  - The Honourable Tony Abbott
  Donald Hoffman:
  - Dr. Donald Hoffman
  Richard Lindzen:
  - Dr. Richard Lindzen
  Yoram Hazony:
  - Dr. Yoram Hazony
  Julie Ponesse:
  - Dr. Julie Ponesse
  Sylvain Charlebois:
  - Dr. Sylvain Charlebois
  Derek Reimer:
  - Pastor Derek Reimer
unresolved_handles:
- mistersunshinebaby
- MisterWhite
- the pleb
- Endeavour
- Billboard Chris
- The Distributist
- An0maly
do_not_merge:
- - Ian Sénéchal
  - Frank
- - Ian Sénéchal
  - François Fournier
- - Stéphane Hamel
  - Amélie Paul
